src/js/cardModal.js
src/partials/cardModal.html
src/sass/components/_filmInfoModal.scss
src/templates/modalTemplate.hbs

Закриття модалки через кнопку. 
Не зміг свг. кнопки виправити, її не видно.

closeBtn Modal

---

src/templates/modalTemplate.hbs

Revert "Update modalTemplate.hbs"

---

src/js/addToStorage.js
src/js/cardModal.js

Поправила функціонал кнопок після зміни модалки

fixed btn add to watched&queue

---

src/js/addToStorage.js
src/js/cardModal.js
src/js/renderFromStorage.js

Функціонал зміни назви кнопок при відкритті модалки, в залежності від того, є фільм в стореджі чи ні

change function btn

---

src/js/index.js
src/js/pagination.js
src/js/renderCards.js

популярні підвантажуються один раз і з жанрами
папку renderCards треба видалити, але я її тільки закоментувала
після того як ти приймеш, зроблю лоадер

Fix loading of popular cards

---

src/js/renderCards.js
src/js/searchByKeyword.js
src/templates/cardTemplate.hbs

Revert "Origin/fix bags"

---

src/js/index.js
src/js/pagination.js
src/js/renderCards.js

Revert "Fix loading of popular cards"

---

src/js/renderCards.js
src/js/searchByKeyword.js
src/templates/cardTemplate.hbs

all render

---

src/js/renderFromStorage.js
src/partials/libraryPageHeader.html
src/sass/base/_buttons.scss
src/sass/layout/_pageHeader.scss

Revert "libraryBtnStyles added"

---

src/js/renderFromStorage.js
src/partials/libraryPageHeader.html
src/sass/base/_buttons.scss
src/sass/layout/_pageHeader.scss

Revert "Revert "libraryBtnStyles added""

---

src/js/paginationS.js

Revert "add S to ARROW str149 maine"

---

src/js/renderCards.js
src/js/searchByKeyword.js

Revert "did a rearrangement of 2 fucntions"

---

src/js/renderFromStorage.js
src/partials/libraryPageHeader.html
src/sass/base/_buttons.scss
src/sass/layout/_pageHeader.scss

Revert "Revert "Revert "libraryBtnStyles added"""

---

src/js/renderCards.js
src/js/searchByKeyword.js
src/templates/cardTemplate.hbs

Revert "all render"

---

src/js/paginationS.js

Revert "Revert "add S to ARROW str149 maine""

---

src/js/renderCards.js
src/js/searchByKeyword.js
src/templates/cardTemplate.hbs

Revert "Revert "all render""

---

src/js/actionLibrary.js
src/js/addToStorage.js
src/js/renderFromStorage.js

Зробила дефолтну загрузку фільмів зі стореджа Watched на сторінці Library.
Виправила вивід жанрів на сторінці Library і по кнопкам Watched&Queue
Зробила рендерінг заднього плану сторінки при активній модалці, якщо ми знаходимось на сторінках Library

changes renderingLibrary

---

src/js/actionLibrary.js
src/js/addToStorage.js
src/js/renderFromStorage.js
src/templates/cardTemplateLibrary.hbs

Створила шаблон тільки для сторінки Library, адже після останніх змін на головній сторінці не працює мій рендеринг на сторінках Library.
Також пофіксила перезагрузку заднього плану при відкритій модалці на Library

change template for library

---

src/js/actionLibrary.js
src/js/renderFromStorage.js

bugfix template

---

src/sass/components/_loader.scss

я замінила спінер, він такий як був на тій версії, але більший

loader styles

---

src/js/apiServiceMovies.js
src/js/onSearchByName.js

Reverts brugiiii/TeamSeven#107

Revert "search pagination"
